Task 1

Write a program that allows you to enter 4 numbers and stores them in a file called “Numbers”

•	3
•	45
•	83
•	21

Have a go at ‘w’ ‘r’  ‘a’



In [ ]:
#Task 1 'w'

my_file = open("numbers.txt","w")

print("please enter 4 numbers: 3, 45, 83, 21")

no_1 = input(str(""))
my_file.write(no_1)
my_file.write("\n")

no_2 = input(str(""))
my_file.write(no_2)
my_file.write("\n")

no_3 = input(str(""))
my_file.write(no_3)
my_file.write("\n")

no_4 = input(str(""))
my_file.write(no_4)
my_file.write("\n")

my_file.close()

please enter 4 numbers: 3, 45, 83, 21
1
2
3
4


In [ ]:
#Task 1 'r'

with open("numbers.txt", "r") as myfile:
    data = myfile.read()

myfile.close()

print(data)

1
2
3
4
This is appended to a file



In [ ]:
#Task 1 'a'

my_file = open("numbers.txt", "a")

my_file.write("This is appended to a file\n")

my_file.close()

Task 2

Write a program to ask a student for their percentage mark and convert this to a grade

The conversion will be done in a function called mark_grade

Extension to Task 2

Ask the user for their target grade and print this with their mark

If their target grade > exam grade display a suitable message

If their target grade = exam grade display a suitable message

If their target grade < exam grade display a suitable message


In [ ]:
#Task 2

def user(input_name):

  print("Hello", input_name + "!" , "Please enter your percentage mark?", "\n")

name = input("What is your name? ")

user(name)

percentage_mark = float(input("enter % mark = "))
print("\n")
print("Grade description:")
print("70% to 100%: This is grade A")
print("60% to 69% : This is grade B")
print("40% to 59% : This is grade C")
print("0% to 39%  : No award", "\n")

target_grade = input("What is your target grade i.e. A, B, C: ")
print("\n")

def mark_grade(target_grade): #Extension to Task 2
  
  if percentage_mark >= 70 and percentage_mark <= 100:
    if target_grade == "A":
      print("A is highest grade")
    else:
      print("The grade is not match")    
  elif percentage_mark >= 60 and percentage_mark <= 69:
    if target_grade == "B":
      print("B is very strong pass")
    else:
      print("The grade is not match")
  elif percentage_mark >= 40 and percentage_mark <= 59:
    if target_grade == "C":
      print("C is pass")
    else:
      print("The grade is not match")
  elif percentage_mark >= 0 and percentage_mark <= 39:
      print("No award")
  else: #no choice of target_grade
    print("You have not typed a valid grade, please run the program again.")
    
calculate = target_grade

mark_grade(calculate)



What is your name? A
Hello A! Please enter your percentage mark? 

enter % mark = 100


Grade description:
70% to 100%: This is grade A
60% to 69% : This is grade B
40% to 59% : This is grade C
0% to 39%  : No award 

What is your target grade i.e. A, B, C: A


A is highest grade


Task 3

1. Create a 1D array of numbers from 0 to 9
2. Create a 3×3 NumPy array of all Boolean value Trues
3. Extract all odd numbers from array of 1-10
4. Replace all odd numbers in an array of 1-10 with the value -1
5. Convert a 1D array to a 2D array with 2 rows
6. Create two arrays a and b, stack these two arrays vertically use the  np.dot and np.sum to calculate totals

Extension to Task 3

1. Create the following pattern without hardcoding. Use only NumPy  functions.
    #>array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
2. In two arrays a (1,2,3,4,5) and b (4,5,6,7,8,9) – remove all repeating  items present in array b
3. Get all items between 3 and 7 from a and b and sum them together



In [142]:
#Task 3

first_1D_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] #1. create 1D array of numbers from 0 to 9

for row in range(len(first_1D_list[0:1])):
    for column in range(len(first_1D_list)):
        print("My list at row", row, "and column", column, "is:", first_1D_list[column])

My list at row 0 and column 0 is: 0
My list at row 0 and column 1 is: 1
My list at row 0 and column 2 is: 2
My list at row 0 and column 3 is: 3
My list at row 0 and column 4 is: 4
My list at row 0 and column 5 is: 5
My list at row 0 and column 6 is: 6
My list at row 0 and column 7 is: 7
My list at row 0 and column 8 is: 8
My list at row 0 and column 9 is: 9


In [2]:
import numpy as np                                                  #quicker to type np than NumPy

boolean = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]], dtype=bool) #2. create a 3×3 NumPy array of all Boolean value Trues
print(boolean)
print("\n", "Values other than 0, none i.e. '', False, or empty strings i.e. "" are considered True")


[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]

 Values other than 0, none i.e. '', False, or empty strings i.e.  are considered True


In [135]:
odd = np.arange(1, 10, 2) #3. extract all odd numbers from array of 1-10
print(odd)                #show odd numbers of 1-10

[1 3 5 7 9]


In [136]:
odd[0:] = -1  #4. replace all odd numbers in an array of 1-10 with the value -1
print(odd)    #assigns array element row 0 the value -1

[-1 -1 -1 -1 -1]


In [159]:
second_1D_list = np.array([first_1D_list])  #5. convert a 1D array to a 2D array with 2 rows
my_2D_list = second_1D_list.reshape(2, 5)
print(my_2D_list)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
a = np.arange(1, 10).reshape(3, 3)  #6. create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals
b = np.arange(10, 19).reshape(3, 3)
c = np.vstack((a, b))               #stacks array vertically (row wise)
print(c)
d = np.dot(a, b)                    #matrix multiplication of 2 matrice of the same size
print(d)
e = np.sum(d)                       #overall sum of all elements
print(e)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
1944


In [181]:
#Extension to Task 3

one_1s = np.ones(3)
print(one_1s)

two_2s = np.add(one_1s, 1)
print(two_2s)

three_3s = np.multiply(one_1s, 3)
print(three_3s)

arange = np.arange(1, 4)
print(arange)

repeat = np.tile(arange, 3)                                   #generate a new ndarray in which the original ndarray is repeatedly arranged
print(repeat)

pattern = np.concatenate((one_1s, two_2s, three_3s, repeat))  #1. create patern of array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
print(pattern)

[1. 1. 1.]
[2. 2. 2.]
[3. 3. 3.]
[1 2 3]
[1 2 3 1 2 3 1 2 3]
[1. 1. 1. 2. 2. 2. 3. 3. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3.]


In [208]:
a = [1, 2, 3, 4, 5]
b = [4, 5, 6, 7, 8, 9]
print(a, np.delete(b, [0, 1]))  #2. remove all repeating items present in array b

[1, 2, 3, 4, 5] [6 7 8 9]


In [217]:
c = np.concatenate((a, b))
print(c[2:9], np.sum(c[2:9])) #3. get all items between 3 and 7 from a and b and sum them together

[3 4 5 4 5 6 7] 34
